package com.ragl.divide.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF22884B)
val onPrimaryLight = Color(0xFFffffff)
val primaryContainerLight = Color(0xFFf3f4f6)
val onPrimaryContainerLight = Color(0xFF000000)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF000000)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val primaryDark = Color(0xFF13B952)
val onPrimaryDark = Color(0xFFffffff)
val primaryContainerDark = Color(0xFF202531)
val onPrimaryContainerDark = Color(0xFFffffff)
val backgroundDark = Color(0xFF141922)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF141922)
val onSurfaceDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFBA1A1A)
val onErrorDark = Color(0xFFFFFFFF)
val errorContainerDark = Color(0xFFFFDAD6)
val onErrorContainerDark = Color(0xFF410002)