name: Build Release Bundle

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
        
    - name: Create keystore.properties
      run: |
        echo "storeFile=divide-release-key.jks" > keystore.properties
        echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> keystore.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
        
    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > divide-release-key.jks
        
    - name: Create google-services.json
      run: |
        echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > composeApp/google-services.json
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build release bundle
      run: ./gradlew bundleRelease
      
    - name: Upload bundle as artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-bundle-${{ github.sha }}
        path: composeApp/build/outputs/bundle/release/composeApp-release.aab
        retention-days: 7
        
    - name: Comment PR with bundle info
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = 'composeApp/build/outputs/bundle/release/composeApp-release.aab';
          const stats = fs.statSync(path);
          const fileSizeInBytes = stats.size;
          const fileSizeInMegabytes = (fileSizeInBytes / (1024*1024)).toFixed(2);
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🎉 **Bundle generado exitosamente!**
            
            📦 **Tamaño del bundle:** ${fileSizeInMegabytes} MB
            📥 **Artifact:** \`release-bundle-${{ github.sha }}\`
            
            El bundle está disponible en los artifacts de este workflow por 7 días.`
          }); 